[ERROR] - ['Traceback (most recent call last):\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 38, in _inner\n    return fn(*args)  # TODO: Confirm\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 57, in multiple\n    return contador.read_multiple(pool, save)\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 274, in read_multiple\n    results = pool.map(_multiple, users)\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map\n    return self._map_async(func, iterable, mapstar, chunksize).get()\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get\n    raise self._value\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar\n    return list(map(*args))\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 267, in _multiple\n    username=user["username"], password=user["password"], driver=browser_setup(),\n', "KeyError: 'username'\n"]
[ERROR] - ['Traceback (most recent call last):\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 38, in _inner\n    return fn(*args)  # TODO: Confirm\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 57, in multiple\n    return contador.read_multiple(pool, save)\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 274, in read_multiple\n    results = pool.map(_multiple, users)\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map\n    return self._map_async(func, iterable, mapstar, chunksize).get()\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get\n    raise self._value\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar\n    return list(map(*args))\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 267, in _multiple\n    username=user["username"], password=user["password"], driver=browser_setup(),\n', "KeyError: 'username'\n"]
[ERROR] - ['Traceback (most recent call last):\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 38, in _inner\n    return fn(*args)  # TODO: Confirm\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 57, in multiple\n    return contador.read_multiple(pool, save)\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 274, in read_multiple\n    results = pool.map(_multiple, users)\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map\n    return self._map_async(func, iterable, mapstar, chunksize).get()\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get\n    raise self._value\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar\n    return list(map(*args))\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 267, in _multiple\n    username=user["username"], password=user["password"], driver=browser_setup(),\n', "KeyError: 'username'\n"]
[ERROR] - ['Traceback (most recent call last):\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 38, in _inner\n    return fn(*args)  # TODO: Confirm\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 57, in multiple\n    return contador.read_multiple(pool, users, save)\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 275, in read_multiple\n    results = pool.map(_multiple, users)\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map\n    return self._map_async(func, iterable, mapstar, chunksize).get()\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get\n    raise self._value\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar\n    return list(map(*args))\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 267, in _multiple\n    username=user["username"], password=user["password"], driver=browser_setup(),\n', "KeyError: 'username'\n"]
[ERROR] - ['Traceback (most recent call last):\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 38, in _inner\n    return fn(*args)  # TODO: Confirm\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/run.py", line 57, in multiple\n    return contador.read_multiple(pool, users, save)\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 275, in read_multiple\n    results = pool.map(_multiple, users)\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map\n    return self._map_async(func, iterable, mapstar, chunksize).get()\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get\n    raise self._value\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\n', '  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar\n    return list(map(*args))\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 267, in _multiple\n    username=user["username"], password=user["password"], driver=browser_setup(),\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/scrapper/contador.py", line 92, in browser_setup\n    profile.native_events_enabled = cfg["native_events_enabled"]\n', '  File "/home/somnium/Desktop/CODE/Projects/CV/contador/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 164, in native_events_enabled\n    raise WebDriverException("Please pass in a Boolean to this call")\n', 'selenium.common.exceptions.WebDriverException: Message: Please pass in a Boolean to this call\n\n']
